Implement vectorized log-likelihood computation to speed up cvxpy.
YosefLab/Cassiopeia pull request #192
Opened 2023-03-14 22:49 UTC by sprillo

As title.

With the new implementation, branch length estimation should be ~10-20x faster.

I have extended `IIDExponentialMLE`'s API with a private argument that toggles between the vectorized and non-vectorized implementations, to be able to profile the difference.

As I have observed in the past, the ECOS solver benefits the most from vectorization (SCS instead performs the same...). Because of this, I have decided to make the ECOS solver (with vectorization) the default one. In this sense, this PR is non-backwards compatible - since the default solver used to be SCS - but it's fine since out method has not been published yet. Unfortunately, the ECOS solver is not as stable as SCS and can sometimes fails (say 5% of the time). Because of this, I have extended the API of the branch length estimator to include a `backup_solver`. If the main `solver` fails, we retry with the backup solver. With the new API's default arguments, the main solver is ECOS, and if it fails, the slower but reliable SCS solver will be used.

NOTE: switching to the ECOS solver on its own speeds up the branch length estimator by ~7x, the remaining ~2-3x being provided by vectorization. The reason I did not use ECOS originally is because SCS is extremely robust; however, we want something faster for dealing with site rate variation now, so the new scheme of ECOS + fallback to SCS should be awesome.

Test plan:
- All old tests pass.
- The following code snippet profiles branch length estimation on a tree with 512 leaves, using either SCS or ECOS, and a vectorized or non-vectorized implementation (for a total of 4 combinations):
```
import time

from cassiopeia.simulator import CompleteBinarySimulator, Cas9LineageTracingDataSimulator
from cassiopeia.tools.branch_length_estimator import IIDExponentialMLE

tree = CompleteBinarySimulator(num_cells=512).simulate_tree()
Cas9LineageTracingDataSimulator(mutation_rate=1.0, random_seed=0).overlay_data(tree)
for solver in ["SCS", "ECOS"]:
    for _use_vectorized_implementation in [False, True]:
        st = time.time()
        IIDExponentialMLE(
            minimum_branch_length=0.01,
            pseudo_mutations_per_edge=0.1,
            pseudo_non_mutations_per_edge=0.1,
            solver=solver,
            _use_vectorized_implementation=_use_vectorized_implementation,
        ).estimate_branch_lengths(tree)
        et = time.time()
        msg_str= f"Time using solver {solver} and _use_vectorized_implementation={_use_vectorized_implementation}: {et - st}"
        print(msg_str)
```
Output:
```
Time using solver SCS and _use_vectorized_implementation=False: 52.351640939712524
Time using solver SCS and _use_vectorized_implementation=True: 46.90113306045532
Time using solver ECOS and _use_vectorized_implementation=False: 6.936963081359863
Time using solver ECOS and _use_vectorized_implementation=True: 2.934386968612671
```

2023-03-16 06:51 UTC, scimind1729 commented on cassiopeia/tools/branch_length_estimator/_iid_exponential_mle.py
> +                raise IIDExponentialMLEError("Third-party solver failed")
Maybe specifically mention that the backup failed? Or if you think this is sufficiently covered by this coupled with _backup_solver_was_needed then it's fine.

2023-03-16 06:56 UTC, scimind1729 requested changes
LGTM. Might be worth considering comparing the output of the vectorized ECOS and unvectorized SCS solvers on some larger trees to see if they agree, even if we can't solve them by hand.

2023-03-16 06:56 UTC, scimind1729 commented on cassiopeia/tools/branch_length_estimator/_iid_exponential_mle.py
> +                raise IIDExponentialMLEError("Third-party solver failed")
Maybe specifically mention that the backup failed? Or if you think this is sufficiently covered by this coupled with _backup_solver_was_needed then it's fine.

2023-03-17 00:16 UTC, sprillo commented
> LGTM. Might be worth considering comparing the output of the vectorized ECOS and unvectorized SCS solvers on some larger trees to see if they agree, even if we can't solve them by hand.

This is a good point. In the notebook above, the trees all look identical. For the record, this code:
```
import time
import cassiopeia as cas

from cassiopeia.simulator import CompleteBinarySimulator, Cas9LineageTracingDataSimulator
from cassiopeia.tools.branch_length_estimator import IIDExponentialMLE

tree = CompleteBinarySimulator(num_cells=512).simulate_tree()
Cas9LineageTracingDataSimulator(mutation_rate=1.0, random_seed=0).overlay_data(tree)
for solver in ["SCS", "ECOS"]:
    for _use_vectorized_implementation in [False, True]:
        st = time.time()
        IIDExponentialMLE(
            minimum_branch_length=0.01,
            pseudo_mutations_per_edge=0.1,
            pseudo_non_mutations_per_edge=0.1,
            solver=solver,
            _use_vectorized_implementation=_use_vectorized_implementation,
        ).estimate_branch_lengths(tree)
        et = time.time()
        msg_str= f"Time using solver {solver} and _use_vectorized_implementation={_use_vectorized_implementation}: {et - st}"
        print(msg_str)
        cas.pl.plot_matplotlib(
            tree,
            add_root=False,
            depth_key="time",
            extend_branches=False,
        )
```

We can also easily verify that performance is the same in our benchmarking, by trying out the two versions.

2023-03-17 04:55 UTC, scimind1729 approved these changes

2023-03-17 08:08 UTC, merged