Process pipeline richard
YosefLab/Cassiopeia pull request #52
Opened 2021-01-20 00:14 UTC by richardyz98

Hi Matt and Sebastian,
This PR contains only the changes relating to the mapping of integers and the change to numpy indexing over loc and iloc. Also contain are some small miscellaneous changes to the documentation and the implementation, such as removing mutation frequencies as a required input from the perform split method and changing the missing data classifier from string/callable to just directly use the callable. I have shelved the Percolation algorithm for now until the next PR.

Thank you in advance for your comments!

2021-01-26 18:09 UTC, mattjones315 requested changes
Thanks for putting this together.

Lots of comments here that I think need to be resolved before merging it in. A couple of themes -

(1) There should be more tests written to support the new behavior you're introducing around the ability to specify new transformations for weights, new dissimilarity / similarity calculations, and more. I've left notes here and there for this.

(2) There's some better engineering practices you can take advantage of to reduce duplicated code & clean up some of the default behavior. Some variable names should also be eschewed for clarity (e.g., `w` -> `weights`). 

(3) In some cases, it's unclear if you really want to include transformations (e.g., ILP or for NJ). These transformations will change the properties of the dissimilarity function calculation so in this case. For example, I'm not sure it'd be wise to allow the user to specify `sqrt` as the transformation when we'll be adding similarities. It might be more straightforward for this case for a user to specify a dissimilarity function. At the very least, I don't think we should change the behavior of the `ILPSolver` and the `DistanceSolver` until we get a better handle on this.

I believe that's it for now. Let's handle these points and then I'll get back to reviewing the PR.

2021-01-26 18:09 UTC, mattjones315 commented on test/solver_tests/greedy_variants_test.py
>          )
I believe it's this test that fails sporadically (i.e. there's some randomization with the weighting). There are two solutions I can see:

1) set a seed for this test so you know you'll get the same behavior each time
2) come up with a more deterministic test case.

2021-01-26 18:09 UTC, mattjones315 commented on test/solver_tests/neighborjoining_solver_test.py
> +        print(T.edges)
please remove `print` statements from tests.

2021-01-26 18:09 UTC, mattjones315 commented on test/solver_tests/spectral_test.py
> +        )
Lots of potential for sporadic behavior due to randomness in the weights, potentially. Take a look at the comments above with suggestions for dealing with this.

2021-01-30 01:27 UTC, richardyz98 commented on cassiopeia/solver/GreedySolver.py
> +        subset_cm = self.unique_character_matrix[samples, :]
Hey Matt I agree actually. I've updated this functionality, and will update our tests.

2021-01-30 02:41 UTC, richardyz98 commented on cassiopeia/solver/missing_data_methods.py
> +) -> Tuple[List[int], List[int]]:
Hey Matt,
I looked and it wasn't in the original Cassiopeia, but I've implemented it here!

2021-02-01 20:05 UTC, richardyz98 commented on cassiopeia/solver/dissimilarity_functions.py
> +                    d -= w[i][s1[i]] - w[i][s2[i]]
Hi Matt I gave this some deeper thought, and I do think this is the functionality we want here. I will try to explain in standup on 2/2/2021

2021-02-01 23:53 UTC, richardyz98 commented on cassiopeia/solver/GreedySolver.py
> +        subset_cm = self.unique_character_matrix[samples, :]
Hey Matt on second thought, after thinking it through more deeply, I take this back. I think that calculating the frequencies with duplicates included could induce some weird behavior. First of all, I have a small counterexample that shows that you could easily produce a less parsimonious tree with including duplicates than with excluding duplicates. I think that given that duplicates will be placed as sisters in the reconstructed tree, we should view them as a technical artifact that occurs from divisions at the bottom of tree, and not as informative to which mutations occurred at the top of the tree (in the case of greedy) or as to which triplets need to be resolved by a supertree instance (in the case of maxcut).

2021-02-01 23:57 UTC, richardyz98 commented on cassiopeia/solver/GreedySolver.py
> +        subset_cm = self.unique_character_matrix[samples, :]
I'll roll back any changes I've made on this front

2021-02-04 19:02 UTC, merged