General bd simulator
YosefLab/Cassiopeia pull request #95
Opened 2021-05-20 01:29 UTC by richardyz98

Hi Matt,
This is the PR for the use of the generator in the solver, as well as some clerical fixes.

I added one similarity function with tests. Also, in the NeighborJoiningSolver, we were keeping the root node around after the fact and keeping it in the character matrix as a sample. This potentially throws off downstream stuff so I changed it so the root node no longer persists in the character matrix of the reconstructed tree.

Let me know if you have any questions,
Richard

2021-05-25 17:14 UTC, mattjones315 requested changes
This is looking nice Richard!

I've left a few comments here -- mostly around the readability of the code. I'm also concerned with guaranteeing that the node names returned by the generator are unique. Can you take a look at my suggestion and see if it make sense?

Finally, I highly suggest that you organize your engineering efforts a bit better. This PR is from the `general_bd_simulator` branch but it has nothing to do with the simulator. Please create new branches for new ideas / work so it's easier to review, organize, and track over time.

Thanks!

2021-05-25 17:14 UTC, mattjones315 commented on cassiopeia/solver/SharedMutationJoiningSolver.py
> +        names = solver_utilities.node_name_generator()
ditto re: informative name for node name generator

2021-05-25 17:14 UTC, mattjones315 commented on cassiopeia/solver/solver_utilities.py
> +
Some questions on behavior -- 

(1) Every time you call this function does this create a _new_ generator? As in there won't be contamination between generators being used in separate functions right?

(2) What else do you do to ensure that you aren't creating duplicate nodes in the CassiopeiaTree? For example, let's consider a pathological example where a character matrix entries starting with `cassiopeia_internal_node` -- how do we handle this? Is there a more unique identifier that we can use? One possibility is to hash the timestamp and use this as the identifier before the unique integer. Thoughts?

2021-05-27 00:38 UTC, richardyz98 commented on cassiopeia/data/CassiopeiaTree.py
> +        if not all(type(i) == str for i in character_matrix.index):
I think it wouldn't work, as it seems the default dtype for a pandas index is `object`

2021-06-01 23:13 UTC, mattjones315 approved these changes
All of this looks great! Let's merge it in.

2021-06-01 23:13 UTC, merged